apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
      - name: db-creds
        mountPath: /etc/secrets
        readOnly: true
  volumes:
    - name: db-creds
      secret:
        secretName: db-credentials
        # optional: restrict keys / rename files
        items:
          - key: DB_USER
            path: DB_USER
          - key: DB_PASSWORD
            path: DB_PASSWORD
 
        defaultMode: 0440
 